version: "2.2"

services:
  project_name_gen:
    container_name: project_name_gen
    image: nginx:1.17.5
    restart: always
    ports:
      - 80:80
    volumes:
      - ./:/usr/share/nginx/html/

  dictionary_gen:
    container_name: dictionary_gen
    image: python:3.7.3
    volumes:
      - ./dictionary:/dictionary
    command:
      - /bin/bash
      - -c
      - |
        cd /dictionary/dictionary_generator/
        python3 build_dictionary.py
